### ISSUE TITLE
Get `AttributeError: module 's2clientprotocol.sc2api_pb2' has no attribute 'Race'` when try to run `python preprocess.py`

### ISSUE THREAD

**Issue by Techget** [wuhuikai/MSC#6]
Hi, 
   First, thanks for making this repository. 
   And I'm trying to go through the "hard way" to get actions with all details(the parameters), and when I run `python preprocess.py` I get the error as 
```
xuan@blairlab:/datasets/MSC/preprocess$ python3 preprocess.py 
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/xuan/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 20499 -dataDir /home/xuan/StarCraftII/ -tempDir /tmp/sc-zvqnp6rt/ -displayMode 0'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:20499 (20499)
Startup Phase 3 complete. Ready for commands.
W0321 21:03:31.184315 140275951630080 sc_process.py:183] Killing the process.
#Replay:   0%|                            | 0/64395 [00:00<?, ?it/s]Traceback (most recent call last):
  File "preprocess.py", line 89, in <module>
    main()
  File "preprocess.py", line 77, in main
    for player_info in players_info))
  File "preprocess.py", line 77, in <genexpr>
    for player_info in players_info))
AttributeError: module 's2clientprotocol.sc2api_pb2' has no attribute 'Race'
```
I'm using the 3.16.1 version of the game for linux btw.
Could you please have a look on this when you get time, thanks.

**Comment by Techget** [comment]
No worries, I fix it by using `from s2clientprotocol import common_pb2 as sc_common` instead of `sc2api_pb2` to fetch `Role` information.
